### ISSUE TITLE
[BUG] rename-note doesn't use title config

### ISSUE THREAD

**Issue by lhoffjann** [nvim-telekasten/telekasten.nvim#138]
**Please confirm**
- [x] I am running the latest version of this plugin

**Describe the bug**
when renaming a note it only uses the title but not the uuid. I have it set that the note name should be "uuid - title".
The error seems to occur because the function RenameNote just takes the title and adds the extensions but doesnt double check the format with the config file.

**Comment by lambtho12** [comment]
Indeed. `RenameNote`was implemented before the `uuid` stuff and we forgot to modify it accordingly.

As the UUID can be time-based, do you think it is preferable to keep the old one when renaming and just changing the title?

**Comment by lhoffjann** [comment]
I am more or less indifferent tbh. 
I use the `uuid` to have my notes in chronological order order of creation.
For that use-case it would make more sense to keep the old `uuid`.
But the easiest way is probably to call `CreateNote` and add the content to the new file.

**Comment by lhoffjann** [comment]
btw. I will gladly do the implementation myself. But I have to familiarize myself with lua a little bit first, but the problem seems to be good for that

**Comment by lambtho12** [comment]
I guess it should not be that hard to check after a UUID in the filename, especially knowing the config values for `new_note_filename` and `uuid_sep`. 

Basically
1. Extract uuid using regex based on `uuid_sep`and pattern defined with `new_note_filename`
2. In `RenameNote`, call `generate_note_filename` with the newname and uuid

**Comment by lambtho12** [comment]
I am currently implementing a fix, but I just thought about some edge cases.

What should we do if
1. The original note had no UUID but the config now is `title-uuid` or `uuid_title`. Should we create a uuid on the spot?
2. The opposite case. The note has a UUID but the config now is `title`. Should we remove the uuid?

I think this is quite important as it would allow someone to convert all their notes to the new naming convention rather easily. But I may be overlooking something. Does anyone have a suggestion here?

**Comment by lhoffjann** [comment]
Regarding
1. I would add the `uuid` on the spot. It is an additional data point that doesn't hurt and can be deleted if it isn't wanted anymore.
2. Why don't we integrate a User prompt? It may or may not be that the user still cares about the data point but you really can't say that in advance.

**Comment by mrshu** [comment]
Just a friendly ping, was there any update here by any chance?

**Comment by lambtho12** [comment]
Not really. I am very busy at the moment and have absolutely zero time for telekasten unfortunately.
