### ISSUE TITLE
[FR] Add `filename_smallcaps` option

### ISSUE THREAD

**Issue by lambtho12** [nvim-telekasten/telekasten.nvim#311]
See: https://github.com/renerocksai/telekasten.nvim/discussions/310

Add a `filename_smallcaps` so the filename can be formatted properly while the note title is kept intact.
This is just a matter of using `string.lower` at the correct place.
```lua 
myString = string.lower(myString)
```

When the config workflow has been refactored, it would be nice to have something like
```lua
config = {
  filename_format = {
    space_sep = "_",
    small_case = true,
    ...
  }
}
```

**Comment by martinpallmann** [comment]
you could instead also allow for a function that accepts the typed title and returns the filename like it is with the UUID function if I'm not mistaken.

**Comment by lambtho12** [comment]
Yes this is a possibility. But for now let's stick to the simple stuff :smile:
