### ISSUE TITLE
Title template tag shows full path instead of just title

### ISSUE THREAD

**Issue by novakwh** [nvim-telekasten/telekasten.nvim#315]
**Please confirm**
- [ x] I am running the latest version of this plugin

**Tell us about what's bothering you...**
...

If there's already a way to alter this behavior that I haven't figured out, my sincere apologies! 

When creating a new templated note inside a specific directory, using a template that includes the {{title}} tag, the tag outputs the full path including directories. I would rather the tag output leave out the directories and show only the note title.

Example of current behavior:
- I create a new templated note "dir1/dir2/File Name"
-  Inside the chosen template, the {{title}} tag returns "dir1/dir2/File Name"

My preferred behavior would be that the {{title}} tag leave off the directories and show only the file name, eg everything after the last slash. Right now I either have to change the cwd to the directory I wish to put the file in, or create the note in the base notes folder and then move the new file to the correct directory, or edit any instances of the {{title}} output inside the file to remove the directory. 

Thanks for this amazing plugin!

**Comment by lambtho12** [comment]
> If there's already a way to alter this behavior that I haven't figured out, my sincere apologies!

[`:h telekasten.template_files`](https://github.com/nvim-telekasten/telekasten.nvim/blob/319276a7853ff996b7bb1ed4250d8047c84ad29d/doc/telekasten.txt#L947-L983) -> Use `{{shorttitle}}` to trim the path rather than `{{title}}`

Apologies accepted :smile: 

> Thanks for this amazing plugin!

Thank you!

**Comment by lambtho12** [comment]
And soooo sorry for the delay ! I completely missed this report somehow.
