### ISSUE TITLE
[BUG] Not able to to create new notes

### ISSUE THREAD

**Issue by ebourgess** [nvim-telekasten/telekasten.nvim#346]
**Please confirm**
- [ x ] I am running the latest version of this plugin

**Describe the bug**
Whenever I try to create a new note with `Telekasten new_note` I am getting the error.

```
   Error  11:56:18 msg_show.lua_error Error executing vim.schedule lua callback: ...local/share/nvim/lazy/telekasten.nvim/lua/telekasten.lua:185: attempt to index field 'cfg' (a nil value)
stack traceback:
	...local/share/nvim/lazy/telekasten.nvim/lua/telekasten.lua:185: in function 'generate_note_filename'
	...local/share/nvim/lazy/telekasten.nvim/lua/telekasten.lua:2053: in function 'on_create'
	...local/share/nvim/lazy/telekasten.nvim/lua/telekasten.lua:2114: in function 'callback'
	...nvim/lazy/telekasten.nvim/lua/telekasten/utils/files.lua:48: in function 'cb'
	...ocal/share/nvim/lazy/dressing.nvim/lua/dressing/util.lua:206: in function <...ocal/share/nvim/lazy/dressing.nvim/lua/dressing/util.lua:202>
```

**To Reproduce**
1. Start nvim
2. Run `Telekasten new_note`
3. Add title and press Enter

**Expected behavior**
It should be creating  a markdown file. 

**Operating system (please complete the following information):**
 - OS: MacOS

**Comment by ebourgess** [comment]
To add more context, this was working on Friday, but now no longer works since yesterday (Monday)

**Comment by cwinsnes** [comment]
For me the error was that `telekasten.lua` has the line `    if M.cfg.filename_small_case then` (line 185) which should instead be `    if M.Cfg.filename_small_case then`.

i.e. an upper case "C" instead of lower case "c".

**Comment by ebourgess** [comment]
@cwinsnes thanks, will create a pull request for that

**Comment by lambtho12** [comment]
Thank you both for your reactivity!
