### ISSUE TITLE
[FR] FZF-Lua Support

### ISSUE THREAD

**Issue by pyrox0** [nvim-telekasten/telekasten.nvim#92]
**Please confirm**
- [x] I am running the latest version of this plugin

**Is your feature request related to a problem? Please describe.**
I'd like to be able to use ibhagwan/fzf-lua as the finder for telekasten.nvim, but it only seems to support Telescope.nvim

**Describe the solution you'd like**
Fzf-Lua integration into this plugin

**Describe alternatives you've considered**
Using Telescope, but I am already using Fzf-Lua for most things and I'd rather not load 2 big fuzzy finder plugins

**Additional context**
Currently, Fzf-Lua extensions support is not as good as telescope's See ibhagwan/fzf-lua/issues/57 for details
Also, I don't know how tightly integrated Telescope and Telekasten are integrated, so this may be a fairly difficult task.

**Comment by sonjiku** [comment]
>Also, I don't know how tightly integrated Telescope and Telekasten are integrated, so this may be a fairly difficult task.

I think the "tele" from "telekasten" comes from "Telescope". I'm not sure if this is something that would probably happen.

**Comment by lambtho12** [comment]
Indeed, Telekasten is a contraction of "Telescope" and "Zettelkasten". Telescope is tightly integrated in Telekasten and many default setting from telescope are passed to Telekasten. I do no know why @renerocksai decided to force the use of ripgrep though. 

I am speculating, but maybe it is because Telekasten is not just a file finder, but also has the possibility for plaintext search, etc which would require ripgrep.

**Comment by TC72** [comment]
I'm new to this plugin but it seems to have very tight integration with telescope.
I made the full move from fzf to telescope and am very happy.

This extension for Telescope provides good performance and implements fzf syntax:
https://github.com/nvim-telescope/telescope-fzf-native.nvim

It would probably help you with the move over.

**Comment by vinoff** [comment]
> I'm new to this plugin but it seems to have very tight integration with telescope. I made the full move from fzf to telescope and am very happy.
> 
> This extension for Telescope provides good performance and implements fzf syntax: https://github.com/nvim-telescope/telescope-fzf-native.nvim
> 
> It would probably help you with the move over.

Are you using telekasten with lazy and fzf-native? If so, can you share your config telekasten.lua and perhaps telescope.lua?

**Comment by TC72** [comment]
I just followed the installation notes from `telescope-fzf-native.nvim`.

So in my lazy config I have this:

```
    {   
        'nvim-telescope/telescope-fzf-native.nvim',
        build = 'make' 
    },
```

and in my telescope config, this is in my extensions:

```
    extensions = {
        fzf = {
            fuzzy = true,                    -- false will only do exact matching
            override_generic_sorter = true,  -- override the generic sorter
            override_file_sorter = true,     -- override the file sorter
            case_mode = "smart_case",        -- or "ignore_case" or "respect_case"
            -- the default case_mode is "smart_case"
        }
    }

```

TeleKasten relies on telescope to work, there's no config apart from configuring which them to use for some telekasten panels.

Hope that helps.

**Comment by vinoff** [comment]
For some reason, I have the exact same config but I am getting:

```
Error detected while processing VimEnter Autocommands for "*":
Failed to run `config` for telescope.nvim

...m/lazy/telescope.nvim/lua/telescope/_extensions/init.lua:10: 'fzf' extension
doesn't exist or isn't installed: ...hare/nvim/lazy/telescope-fzf-native.nvim/lu
a/fzf_lib.lua:11: /home/vinoff/.local/share/nvim/lazy/telescope-fzf-native.nvi
m/lua/../build/libfzf.so: cannot open shared object file: No such file or direct
ory

# stacktrace:
  - /telescope.nvim/lua/telescope/_extensions/init.lua:10 _in_ **load_extension*
*
  - /telescope.nvim/lua/telescope/_extensions/init.lua:62 _in_ **load_extension*
*
  - ~/.config/nvim/lua/plugins/telescope.lua:117 _in_ **config**
  - ~/.config/nvim/init.lua:32
```

This only happens with telekasten configured:


```lua
return {
	"renerocksai/telekasten.nvim",
	dependencies = { "nvim-telescope/telescope.nvim" },
	config = function()
		require("telekasten").setup({
			home = vim.fn.expand("~/priv/docs/synced_phone/notes/"), -- Put the name of your notes directory here
		})
	end,
}
```

**Comment by vinoff** [comment]
Nevermind, I fixed it by doing `make` in .local/share/nvim/lazy/telescope-fzf-native.nvim.. For some reason, Lazy was not building it properly??

**Comment by pyrox0** [comment]
Closing as I no longer use this plugin anymore
